import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useEffect, useState } from 'react'
const EditorJs = dynamic(() => import('react-editor-js'), { ssr: false })

let editorInstance

const Editor = ({ onSave, selected = null }) => {
  const [title, setTitle] = useState(selected ? selected.title : '')
  const [description, setDescription] = useState(selected ? selected.description : '')
  const [topicId, setTopicId] = useState(selected ? selected.topic_id : '')
  const [editorTools, setEditorTools] = useState<any>()

  const onSaveHandler = async editorInstance => {
    try {
      const blogData = await editorInstance.save()

      if (!title || title === '') throw new Error('Title cannot be empty. Please enter title')
      if (!topicId || topicId === '') throw new Error('Topic ID cannot be empty. Please enter a topic ID')
      if (!blogData.blocks[0]) throw new Error('Blog cannot be empty. Please enter some data')

      onSave({
        blogData,
        title,
        description,
        topicId,
        id: selected ? selected.id : ''
      })
    } catch (err) {
      console.log(err)
    }
  }

  let editorComponent
  if (!editorTools) editorComponent = 'Loading...'
  else {
    editorComponent = (
      <div className='unreset'>
        <EditorJs
          instanceRef={instance => (editorInstance = instance)}
          tools={editorTools}
          placeholder={`Let's write an awesome blog!`}
          data={
            selected
              ? {
                  time: 1556098174501,
                  blocks: selected.data,
                  version: '2.0.0'
                }
              : null
          }
        />
      </div>
    )
  }

  useEffect(() => {
    const importConstants = async () => {
      const tools = (await import('@/components/Editor/EditorConstants')).default
      setEditorTools(tools)
    }

    importConstants()
  }, [])

  const inputStyle = {
    maxWidth: '500px',
    marginBottom: '20px',
    height: '30px'
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column' }}>
      <Head>
        <title>Create Blog</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <input
        style={inputStyle}
        placeholder='Your Blog Title'
        value={title}
        onChange={event => setTitle(event.target.value)}
      />

      {editorComponent}

      <div style={{ textAlign: 'center' }}>
        <button
          type='button'
          className='inline-flex justify-center w-full rounded-md border-2 border-indigo-200 shadow-sm px-4 py-2 bg-white text-base font-medium text-indigo-700 hover:bg-indigo-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:text-sm'
          onClick={() => onSaveHandler(editorInstance)}>
          Save
        </button>
      </div>
    </div>
  )
}

export default Editor
